# ------------------------------------------------
# Generic Makefile
 
 # @author Vamsi Boyella - vboye103@uottawa.ca
 # @author Baji Baba Shaik - bshai015@uottawa.ca
 # @author Matheen Mohammed- MatheenMohammed@cmail.carleton.ca
 # @author Sangamesh Patlolla-SangameshwarPatlolla@cmail.carleton.ca
 
# Date  : 2020-04-15


all:
	gcc main.c admin.c general_design.c ingredients.c -o exefile
clean:
	rm -rf *o exefile



